from .. import Provider as LoremProvider


class Provider(LoremProvider):
    """Lorem provider for Afghanistan (``en_AF``).

    ``en_AF`` is the English-transliteration locale, so its filler text is
    English. The Pashto word list lives in ``pa_AF``.
    """

    word_list = (
        "ability", "able", "about", "above", "accept", "account", "across", "act", "action",
        "add", "address", "after", "again", "against", "age", "agree", "air", "all", "allow",
        "almost", "alone", "along", "already", "also", "always", "among", "amount", "animal",
        "another", "answer", "any", "appear", "apply", "area", "argue", "arm", "around",
        "arrive", "art", "ask", "attack", "attend", "author", "available", "avoid", "away",
        "baby", "back", "bad", "bag", "balance", "ball", "bank", "base", "basis", "become",
        "before", "begin", "behind", "believe", "benefit", "best", "better", "between",
        "beyond", "big", "bill", "bird", "bit", "black", "block", "blood", "blue", "board",
        "body", "book", "border", "both", "box", "boy", "branch", "bread", "break", "bridge",
        "bring", "broad", "brother", "budget", "build", "business", "but", "buy", "call",
        "camp", "capital", "car", "care", "carry", "case", "catch", "cause", "center",
        "central", "century", "certain", "chair", "chance", "change", "chapter", "charge",
        "check", "child", "choice", "choose", "city", "claim", "class", "clean", "clear",
        "close", "cold", "collect", "college", "color", "come", "common", "community",
        "company", "compare", "complete", "concern", "condition", "consider", "contain",
        "continue", "control", "cost", "could", "council", "count", "country", "course",
        "court", "cover", "create", "crop", "cross", "crowd", "culture", "current", "cut",
        "dark", "data", "daughter", "day", "deal", "decide", "deep", "degree", "deliver",
        "demand", "describe", "design", "detail", "develop", "difference", "difficult",
        "direct", "discuss", "district", "doctor", "door", "double", "down", "draw", "dream",
        "drive", "drop", "dry", "during", "duty", "early", "earth", "east", "easy", "eat",
        "edge", "education", "effect", "effort", "eight", "either", "elect", "element",
        "else", "empty", "end", "energy", "engine", "enough", "enter", "entire", "equal",
        "even", "event", "ever", "every", "exact", "example", "except", "exist", "expect",
        "experience", "explain", "eye", "face", "fact", "factory", "fail", "fair", "fall",
        "family", "far", "farm", "fast", "father", "fear", "feed", "feel", "few", "field",
        "fight", "figure", "fill", "film", "final", "find", "fine", "finish", "fire",
        "first", "fish", "fit", "five", "fix", "flat", "floor", "flow", "follow", "food",
        "foot", "force", "forest", "forget", "form", "forward", "four", "free", "fresh",
        "friend", "from", "front", "full", "future", "game", "garden", "gas", "gate",
        "gather", "general", "get", "gift", "girl", "give", "glass", "goal", "gold", "good",
        "govern", "grade", "grain", "grand", "grant", "grass", "great", "green", "grew",
        "ground", "group", "grow", "guard", "guess", "guide", "hair", "half", "hall", "hand",
        "happen", "hard", "head", "health", "hear", "heart", "heat", "heavy", "help", "here",
        "high", "hill", "history", "hold", "hole", "home", "hope", "horse", "hospital",
        "hot", "hour", "house", "however", "huge", "human", "hundred", "idea", "image",
        "imagine", "impact", "import", "improve", "include", "increase", "indeed", "indicate",
        "industry", "inform", "inside", "instead", "interest", "into", "involve", "issue",
        "item", "job", "join", "judge", "just", "keep", "key", "kind", "king", "kitchen",
        "know", "labor", "lack", "land", "language", "large", "last", "late", "laugh", "law",
        "lead", "learn", "least", "leave", "left", "legal", "length", "less", "letter",
        "level", "library", "lie", "life", "light", "like", "limit", "line", "list", "listen",
        "little", "live", "load", "local", "lock", "long", "look", "lose", "loss", "lot",
        "love", "low", "machine", "main", "maintain", "major", "make", "manage", "many",
        "map", "march", "mark", "market", "marry", "material", "matter", "may", "mean",
        "measure", "meat", "media", "medical", "meet", "member", "memory", "mention",
        "message", "metal", "method", "middle", "might", "mile", "milk", "million", "mind",
        "mine", "minister", "minute", "miss", "mix", "model", "modern", "moment", "money",
        "month", "moon", "more", "morning", "most", "mother", "mountain", "mouth", "move",
        "much", "music", "must", "name", "nation", "nature", "near", "necessary", "need",
        "network", "never", "new", "news", "next", "night", "nine", "none", "north", "note",
        "nothing", "notice", "now", "number", "object", "observe", "obtain", "occur",
        "offer", "office", "often", "oil", "old", "once", "only", "open", "operate",
        "opinion", "order", "organize", "other", "out", "outside", "over", "own", "page",
        "pain", "paint", "pair", "paper", "parent", "part", "particular", "party", "pass",
        "past", "path", "pattern", "pay", "peace", "people", "perhaps", "period", "person",
        "phone", "pick", "picture", "piece", "place", "plan", "plant", "play", "please",
        "point", "police", "policy", "political", "poor", "popular", "position", "possible",
        "post", "power", "practice", "prepare", "present", "press", "pressure", "prevent",
        "price", "print", "private", "probably", "problem", "process", "produce", "product",
        "program", "project", "proper", "protect", "prove", "provide", "public", "pull",
        "purpose", "push", "put", "quality", "question", "quick", "quiet", "quite", "radio",
        "raise", "range", "rate", "rather", "reach", "read", "ready", "real", "reason",
        "receive", "recent", "record", "red", "reduce", "refer", "reflect", "region",
        "relate", "release", "remain", "remember", "remove", "repeat", "replace", "report",
        "represent", "require", "research", "respond", "rest", "result", "return", "reveal",
        "rich", "ride", "right", "rise", "risk", "river", "road", "rock", "role", "roll",
        "roof", "room", "root", "round", "rule", "run", "rural", "safe", "salt", "same",
        "sand", "save", "say", "scale", "scene", "school", "science", "score", "sea",
        "search", "season", "seat", "second", "section", "secure", "see", "seek", "seem",
        "sell", "send", "senior", "sense", "separate", "series", "serious", "serve",
        "service", "set", "settle", "seven", "several", "shape", "share", "sheet", "shift",
        "ship", "shop", "short", "should", "show", "side", "sign", "silver", "similar",
        "simple", "since", "sing", "single", "sister", "sit", "site", "situation", "six",
        "size", "skill", "sky", "sleep", "slow", "small", "smile", "snow", "social", "soft",
        "soil", "soldier", "solid", "solve", "some", "son", "song", "soon", "sort", "sound",
        "source", "south", "space", "speak", "special", "speed", "spend", "spring", "staff",
        "stage", "stand", "standard", "star", "start", "state", "station", "stay", "step",
        "still", "stock", "stone", "stop", "store", "story", "straight", "street", "strong",
        "structure", "student", "study", "stuff", "style", "subject", "success", "such",
        "sudden", "suffer", "suggest", "summer", "sun", "supply", "support", "sure",
        "surface", "surprise", "system", "table", "take", "talk", "task", "teach", "team",
        "tell", "ten", "term", "test", "than", "thank", "that", "their", "them", "then",
        "theory", "there", "these", "they", "thing", "think", "third", "this", "those",
        "though", "thought", "thousand", "three", "through", "throw", "thus", "time", "today",
        "together", "tomorrow", "tonight", "too", "tool", "top", "total", "touch", "toward",
        "town", "trade", "train", "travel", "treat", "tree", "trial", "trip", "trouble",
        "true", "trust", "truth", "try", "turn", "twice", "two", "type", "under",
        "understand", "unit", "until", "upon", "urban", "use", "usual", "value", "various",
        "very", "victory", "view", "village", "visit", "voice", "vote", "wait", "walk",
        "wall", "want", "war", "warm", "wash", "watch", "water", "wave", "way", "weak",
        "wear", "weather", "week", "weight", "welcome", "well", "west", "what", "wheat",
        "wheel", "when", "where", "whether", "which", "while", "white", "who", "whole",
        "why", "wide", "wife", "wild", "will", "win", "wind", "window", "wine", "winter",
        "wish", "with", "within", "without", "woman", "wonder", "wood", "word", "work",
        "world", "worry", "worth", "would", "write", "wrong", "yard", "year", "yellow",
        "yes", "yet", "young", "your", "youth",
    )
